#!/bin/bash
export INSTALLDIR=/usr/local/bin
export URL="https://github.com/RPCS3/rpcs3-binaries-linux/releases/download/build-df4fc947ecd37915cedc2a17ace5cc7c3962f423/rpcs3-v0.0.30-16162-df4fc947_linux64.AppImage"
export NAME="rpcs3"

function install {
	# we depend on wget for installs sadly
	wget -O "$INSTALLDIR/$NAME" $URL
	chmod a+x $INSTALLDIR/$NAME
}

function remove {
	cd $INSTALLDIR
	rm $NAME -r
}

install

unset INSTALLDIR
unset URL
unset NAME
